### ISSUE TITLE
Could Minnesota please be added

### ISSUE THREAD

**Issue by ojlaw** [skykep/WME-DOT-Advisories#4]
Would it be possible to add https://511mn.org/ ? With the following info-
I-94 eastbound: Exit ramp closed.
Updated August 18 by MnDOT
At Exit 230 ramp to 4th St. The exit ramp is closed. Bridge construction work is in progress. Follow the detour signs. Until October 1, 2021 at about 5:00PM CDT.

Comment: Mon, May 24 through September, the ramp from EB I-94 to 4th Street is closed. Detour: EB I-94 to 7th St. to 1st Ave. CLICK HERE

Thanks for the consideration.
<img width="524" alt="Screen Shot 2021-09-12 at 3 58 34 PM" src="https://user-images.githubusercontent.com/36800343/133005414-2948eeea-33d9-4788-8ba0-714f0ffc2615.png">

**Comment by skykep** [comment]
Added
